import type { PublicSiteData } from "@platform/theme-engine";

/** Explicit demonstration content. Not a source of operational or commercial truth. */
export const demoSites: Readonly<Record<"classic" | "urban" | "minimal" | "imperial", PublicSiteData>> = {
  classic: { tenant: { id: "tenant-a", name: "Casa do Barbeiro", slug: "casa-do-barbeiro", description: "Um bom corte começa com uma boa conversa. Um espaço dedicado ao seu estilo, com atenção a cada detalhe.", contact: {}, location: { id: "loc-1", address: "Endereço demonstrativo", city: "São Paulo", state: "SP", timezone: "America/Sao_Paulo", mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.0!2d-46.6!3d-23.5!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0!2sbr!5e0!3m2!1spt-BR!2sbr" } }, services: [{ id: "classic-cut", name: "Corte de cabelo", description: "Um corte pensado para você.", durationMinutes: 40 }, { id: "classic-beard", name: "Barba & cuidado", description: "Acabamento e cuidado em cada detalhe.", durationMinutes: 30 }], professionals: [{ id: "classic-team", name: "Rafael Costa", specialty: "Cortes clássicos e contemporâneos" }] },
  urban: { tenant: { id: "tenant-studio", name: "Studio Barber", slug: "studio", description: "Corte é expressão. Encontre seu estilo em um espaço que tem a sua energia.", contact: {}, location: { id: "loc-2", address: "Endereço demonstrativo", city: "Curitiba", state: "PR", timezone: "America/Sao_Paulo", mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.0!2d-46.6!3d-23.5!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0!2sbr!5e0!3m2!1spt-BR!2sbr" } }, services: [{ id: "urban-cut", name: "DEGRADÊ", description: "Precisão no corte, identidade no resultado.", durationMinutes: 45 }, { id: "urban-beard", name: "BARBA", description: "Linhas que fazem a diferença.", durationMinutes: 30 }], professionals: [{ id: "urban-team", name: "Lucas Ferreira", specialty: "Degradê e freestyle" }] },
  minimal: { tenant: { id: "tenant-minimal", name: "Officina Barber", slug: "officina", description: "Menos é mais. Precisão e simplicidade em cada corte.", contact: { phone: "+5511999888777" }, location: { id: "loc-4", address: "Endereço demonstrativo", city: "Florianópolis", state: "SC", timezone: "America/Sao_Paulo", mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.0!2d-46.6!3d-23.5!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0!2sbr!5e0!3m2!1spt-BR!2sbr" } }, services: [{ id: "min-cut", name: "Corte", description: "Lâmina, máquina e atenção.", durationMinutes: 35, priceLabel: "R$ 55,00" }, { id: "min-beard", name: "Barba", description: "Alinhamento e hidratação.", durationMinutes: 25, priceLabel: "R$ 40,00" }, { id: "min-combo", name: "Combo", description: "Corte e barba completos.", durationMinutes: 55, priceLabel: "R$ 85,00" }], professionals: [{ id: "min-team-1", name: "Caio Mendes", specialty: "Cortes e barbas" }, { id: "min-team-2", name: "Bruno Dias", specialty: "Degradê e pigmentação" }] },
  imperial: { tenant: { id: "tenant-imperial", name: "Imperial Barbearia", slug: "imperial", description: "Um refúgio para desacelerar. Uma experiência de cuidado que respeita sua individualidade.", contact: {}, location: { id: "loc-3", address: "Endereço demonstrativo", city: "Belo Horizonte", state: "MG", timezone: "America/Sao_Paulo", mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.0!2d-46.6!3d-23.5!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0!2sbr!5e0!3m2!1spt-BR!2sbr" } }, services: [{ id: "imperial-cut", name: "Corte personalizado", description: "Estilo e precisão em uma experiência de cuidado.", durationMinutes: 50 }, { id: "imperial-beard", name: "Ritual da barba", description: "Preparação, desenho e acabamento.", durationMinutes: 40 }], professionals: [{ id: "imperial-team", name: "André Almeida", specialty: "Cortes e visagismo" }] },
};
