/** Scoped to the visual renderer, independent of admin and dashboard. */
export const studioStyles = `
.brand-studio{--brand-width:1180px;--brand-heading:clamp(2.8rem,6.5vw,6.4rem);--brand-line:color-mix(in srgb,var(--theme-text) 18%,transparent);-webkit-text-size-adjust:100%;text-size-adjust:100%}
.brand-studio[data-width=narrow]{--brand-width:980px}.brand-studio[data-width=wide]{--brand-width:1440px}
.brand-studio[data-scale=restrained]{--brand-heading:clamp(2.4rem,5vw,4.5rem)}.brand-studio[data-scale=dramatic]{--brand-heading:clamp(3.3rem,8vw,8rem)}
.brand-studio .brand-container{width:min(var(--brand-width),calc(100% - 64px));margin-inline:auto}
.brand-studio h1,.brand-studio h2,.brand-studio h3{font-family:var(--theme-heading-font);font-weight:400;overflow-wrap:anywhere}
.brand-studio[data-case=uppercase] h1,.brand-studio[data-case=uppercase] h2{text-transform:uppercase}
.brand-studio .brand-nav{display:flex;flex-wrap:wrap;align-items:center;gap:24px;padding-block:28px;border-bottom:1px solid var(--brand-line)}
.brand-studio .brand-identity{display:grid;gap:8px;min-width:0;flex:1}.brand-studio .brand-name{font-family:var(--theme-heading-font);font-size:26px;line-height:1.2;overflow-wrap:anywhere}
.brand-studio .brand-tagline{font-size:10px;text-transform:uppercase;letter-spacing:.15em;overflow-wrap:anywhere}
.brand-studio .brand-logo{object-fit:contain;object-position:left!important;width:auto;max-width:min(220px,100%);height:64px}
.brand-studio .brand-nav nav{display:flex;flex-wrap:wrap;gap:12px 24px;max-width:60%;font-size:12px}.brand-studio .brand-nav nav a{padding:8px 0;border-bottom:1px solid transparent;overflow-wrap:anywhere}.brand-studio .brand-nav nav a:hover{border-color:currentColor}
.brand-studio[data-navigation=centered] .brand-nav{flex-direction:column;text-align:center}.brand-studio[data-navigation=centered] .brand-nav nav{justify-content:center;max-width:100%}.brand-studio[data-navigation=centered] .brand-logo{margin:auto}.brand-studio[data-navigation=centered] .brand-nav-cta{display:none}
.brand-studio[data-navigation=minimal] .brand-nav nav{display:none}
.brand-studio .brand-button{display:inline-flex;align-items:center;justify-content:center;gap:28px;padding:16px 24px;border:1px solid var(--theme-primary);background:var(--theme-primary);color:var(--theme-on-primary);border-radius:var(--theme-radius);font-size:13px;font-weight:600;line-height:1.5;min-height:48px;text-align:center;max-width:100%;overflow-wrap:anywhere}
.brand-studio[data-buttons=outline] .brand-button{background:transparent;color:var(--theme-text);border-color:currentColor}.brand-studio .brand-button:hover{transform:translateY(-2px)}
.brand-studio .brand-nav-cta{padding:12px 18px;font-size:11px}.brand-studio .brand-hero{display:grid;grid-template-columns:1.05fr 1fr;gap:clamp(28px,5vw,88px);align-items:center;padding-block:var(--theme-space)}
.brand-studio .brand-eyebrow{font-size:11px;letter-spacing:.18em;text-transform:uppercase;line-height:1.8;margin:0 0 24px;overflow-wrap:anywhere}
.brand-studio .brand-hero h1{font-size:var(--brand-heading);line-height:1.04;letter-spacing:-.045em;margin:0 0 28px;text-wrap:balance}
.brand-studio .brand-intro{white-space:pre-line;max-width:560px;line-height:1.85;font-size:clamp(15px,1.3vw,18px);margin:0 0 32px;overflow-wrap:anywhere}
.brand-studio .brand-hero-art{min-width:0;aspect-ratio:4/5;overflow:hidden;border-radius:var(--theme-radius);background:var(--theme-surface)}
.brand-studio .brand-image{width:100%;height:100%;display:block;object-fit:cover}.brand-studio .brand-image-fallback{width:100%;height:100%;min-height:100px;display:grid;place-content:center;text-align:center;padding:24px;border:1px solid var(--brand-line);overflow-wrap:anywhere}
.brand-studio[data-shape=arch] .brand-hero-art{border-radius:50% 50% 0 0}.brand-studio[data-shape=organic] .brand-hero-art{border-radius:40% 8% 35% 8%}
.brand-studio .brand-monogram{height:100%;min-height:280px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:30px;background:linear-gradient(145deg,color-mix(in srgb,var(--theme-primary) 12%,var(--theme-surface)),var(--theme-surface));border:1px solid var(--brand-line);padding:32px;color:var(--theme-text)}
.brand-studio .brand-monogram>span{font-family:var(--theme-heading-font);font-size:clamp(70px,12vw,180px);line-height:1;letter-spacing:-.07em;border-block:1px solid var(--brand-line);padding:40px 12px}.brand-studio .brand-monogram small{font-size:10px;letter-spacing:.17em;text-transform:uppercase;text-align:center;overflow-wrap:anywhere}
.brand-studio .brand-hero[data-layout=centered],.brand-studio .brand-hero[data-layout=compact]{grid-template-columns:1fr;text-align:center}.brand-studio .brand-hero[data-layout=centered] .brand-hero-copy,.brand-studio .brand-hero[data-layout=compact] .brand-hero-copy{max-width:960px;margin:auto}.brand-studio .brand-hero[data-layout=centered] .brand-intro,.brand-studio .brand-hero[data-layout=compact] .brand-intro{margin-inline:auto}.brand-studio .brand-hero[data-layout=centered] .brand-hero-art{width:min(760px,100%);aspect-ratio:16/9;margin:auto}.brand-studio .brand-hero[data-layout=compact]{padding-block:48px}.brand-studio .brand-hero[data-layout=compact] .brand-hero-art{aspect-ratio:21/9}
.brand-studio .brand-hero[data-layout=editorial]{grid-template-columns:1.25fr 1fr;align-items:start}.brand-studio .brand-hero[data-layout=editorial] .brand-hero-art{margin-top:64px;aspect-ratio:3/4}.brand-studio .brand-hero[data-layout=editorial] .brand-hero-copy{padding-top:12px}
.brand-studio .brand-hero[data-layout=poster]{grid-template-columns:1fr;padding-block:32px var(--theme-space);gap:0}.brand-studio .brand-hero[data-layout=poster] .brand-hero-copy{grid-area:1/1;z-index:1;align-self:end;position:relative;margin:clamp(20px,5vw,72px);padding:clamp(24px,4vw,56px);max-width:860px;background:var(--theme-background);border:1px solid var(--brand-line)}.brand-studio .brand-hero[data-layout=poster] .brand-hero-art{grid-area:1/1;aspect-ratio:16/10;min-height:640px;border-radius:var(--theme-radius)}
.brand-studio .brand-hero[data-layout=fullscreen]{grid-template-columns:1fr;min-height:100vh;position:relative;text-align:center;padding:0}
.brand-studio .brand-hero[data-layout=fullscreen] .brand-hero-copy{position:relative;z-index:2;max-width:900px;margin:auto;padding:clamp(80px,12vh,160px) 24px}
.brand-studio .brand-hero[data-layout=fullscreen] .brand-hero-art{position:absolute;inset:0;z-index:1}
.brand-studio .brand-hero[data-layout=fullscreen] .brand-hero-art::after{content:'';position:absolute;inset:0;background:linear-gradient(to bottom,color-mix(in srgb,var(--theme-background) 40%,transparent),var(--theme-background))}
.brand-studio .brand-hero[data-layout=fullscreen] .brand-intro{margin-inline:auto}
.brand-studio .brand-hero[data-layout=fullscreen] h1{color:var(--theme-text)}
.brand-studio .brand-hero[data-layout=diagonal]{grid-template-columns:1fr 1fr;gap:0;position:relative;overflow:hidden}
.brand-studio .brand-hero[data-layout=diagonal] .brand-hero-copy{padding:var(--theme-space) 48px var(--theme-space) 0;position:relative;z-index:2}
.brand-studio .brand-hero[data-layout=diagonal] .brand-hero-art{clip-path:polygon(15% 0,100% 0,100% 100%,0 100%);aspect-ratio:auto;min-height:500px}
.brand-studio .brand-section{padding:var(--theme-space) 0;scroll-margin-top:24px}.brand-studio[data-separators=line] .brand-section{border-top:1px solid var(--brand-line)}.brand-studio .brand-section[data-tone=surface]{background:var(--theme-surface)}.brand-studio .brand-section[data-tone=accent]{background:color-mix(in srgb,var(--theme-accent) 12%,var(--theme-background))}
.brand-studio .brand-section[data-spacing=compact]{padding-block:40px}.brand-studio .brand-section[data-spacing=comfortable]{padding-block:72px}.brand-studio .brand-section[data-spacing=generous]{padding-block:112px}
.brand-studio .brand-section-intro{max-width:740px;margin-bottom:36px}.brand-studio .brand-section h2{font-size:clamp(2rem,4vw,3.8rem);line-height:1.13;letter-spacing:-.035em;margin:0 0 24px;text-wrap:balance}.brand-studio .brand-prose{font-size:16px;line-height:1.85;overflow-wrap:anywhere}.brand-studio .brand-prose p{white-space:pre-line;margin:0 0 20px}
.brand-studio .brand-section[data-align=center] .brand-section-intro{margin-inline:auto;text-align:center}.brand-studio .brand-section-layout[data-composition=split]{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.5fr);gap:48px;align-items:start}.brand-studio .brand-section-content{min-width:0}.brand-studio .brand-section-content:empty{display:none}
.brand-studio .brand-team{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(240px,100%),1fr));gap:32px}.brand-studio .brand-story-image{aspect-ratio:4/3;margin:0 0 28px;overflow:hidden;border-radius:var(--theme-radius)}
.brand-studio .brand-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}.brand-studio .brand-gallery figure{margin:0;min-width:0}.brand-studio .brand-gallery .brand-image,.brand-studio .brand-gallery .brand-image-fallback{aspect-ratio:4/3;height:auto;border-radius:var(--theme-radius)}.brand-studio .brand-gallery figcaption{font-size:12px;margin-top:12px;overflow-wrap:anywhere}
.brand-studio .brand-footer-note{padding-top:32px;font-size:15px;white-space:pre-line;overflow-wrap:anywhere}.brand-studio address{padding:28px;border:1px solid var(--brand-line);border-radius:var(--theme-radius);overflow-wrap:anywhere}.brand-studio .brand-empty{border:1px dashed var(--brand-line);padding:24px}
.brand-studio .price-card,.brand-studio .price-table{border-radius:var(--theme-radius)}.brand-studio .price-card h3{font-family:var(--theme-heading-font)}.brand-studio .price-table{table-layout:fixed}.brand-studio .price-table th:first-child{width:53%}.brand-studio .price-table td{overflow-wrap:anywhere}.brand-studio .price-table tr:last-child td{border-bottom:0}.brand-studio .price-table td:last-child{white-space:normal}.brand-studio .price-value{color:var(--theme-text);font-size:clamp(22px,3vw,32px)}
.brand-studio[data-cards=minimal] .price-card{background:transparent;border:0;border-top:1px solid var(--brand-line);border-radius:0;padding-inline:0}.brand-studio[data-cards=elevated] .price-card{box-shadow:0 16px 40px color-mix(in srgb,var(--theme-text) 9%,transparent);border-color:transparent}
@media(max-width:1000px){.brand-studio .brand-nav-cta{display:none}.brand-studio[data-navigation=minimal] .brand-nav-cta{display:inline-flex}.brand-studio .brand-section-layout[data-composition=split]{grid-template-columns:1fr;gap:8px}.brand-studio .price-grid{grid-template-columns:1fr}}
@media(max-width:700px){.brand-studio .brand-container{width:calc(100% - 40px)}.brand-studio .brand-nav{gap:20px;padding-block:22px}.brand-studio .brand-nav nav{max-width:100%;width:100%;gap:4px 18px}.brand-studio .brand-hero,.brand-studio .brand-hero[data-layout=editorial]{grid-template-columns:1fr;gap:32px;padding-block:48px}.brand-studio .brand-hero h1{font-size:clamp(2.7rem,10vw,4.4rem)}.brand-studio[data-scale=restrained] .brand-hero h1{font-size:2.6rem}.brand-studio[data-scale=dramatic] .brand-hero h1{font-size:clamp(3rem,12vw,5rem)}.brand-studio .brand-hero-art,.brand-studio .brand-hero[data-layout=editorial] .brand-hero-art{margin:0;aspect-ratio:4/3}.brand-studio .brand-hero[data-layout=poster]{display:flex;flex-direction:column-reverse;gap:0}.brand-studio .brand-hero[data-layout=poster] .brand-hero-art{min-height:0;aspect-ratio:4/3;width:100%}.brand-studio .brand-hero[data-layout=poster] .brand-hero-copy{margin:-24px 12px 0;padding:24px}.brand-studio .brand-hero[data-layout=fullscreen]{min-height:80vh}.brand-studio .brand-hero[data-layout=diagonal]{grid-template-columns:1fr}.brand-studio .brand-hero[data-layout=diagonal] .brand-hero-art{clip-path:none;aspect-ratio:4/3}.brand-studio .brand-hero[data-layout=diagonal] .brand-hero-copy{padding:48px 0}.brand-studio .brand-section{padding-block:48px}.brand-studio .brand-section[data-spacing=generous]{padding-block:72px}.brand-studio .brand-gallery{gap:24px;grid-template-columns:1fr}.brand-studio .brand-button{gap:18px}.brand-studio .price-table th,.brand-studio .price-table td{padding:16px 8px}.brand-studio .price-table th{font-size:10px;letter-spacing:.04em}}
@media(prefers-reduced-motion:reduce){.brand-studio .brand-button:hover{transform:none}}
`;
