import type { DesignTokenOverrides } from '@platform/design-system';
import { siteEditorConfigSchema, type SiteContent, type SiteEditorConfig } from './site-editor';

export interface DesignDirection {
  id: string;
  name: string;
  description: string;
  tokens: DesignTokenOverrides;
  heroLayout: SiteContent['heroLayout'];
  appearance: NonNullable<SiteContent['appearance']>;
}

/** Starting points for a brand, independent of theme ownership and operational features. */
export const designDirections: readonly DesignDirection[] = [
  { id: 'atelier', name: 'Ateliê editorial', description: 'Papel claro, verde profundo e títulos com espaço para respirar.', heroLayout: 'editorial', appearance: { width: 'wide', navigation: 'inline', headingScale: 'expressive', headingCase: 'natural', imageShape: 'rectangle', separators: 'line' }, tokens: { primaryColor: '#283E35', secondaryColor: '#66665E', accentColor: '#895E35', backgroundColor: '#F5F1E8', surfaceColor: '#FFFCF5', textColor: '#28362E', fontHeading: 'serif', fontBody: 'sans', borderRadius: 'none', buttonStyle: 'outline', cardStyle: 'minimal', spacingScale: 'generous', animationPreset: 'none' } },
  { id: 'nocturne', name: 'Clube noturno', description: 'Contraste escuro, detalhes de bronze e uma capa de impacto.', heroLayout: 'poster', appearance: { width: 'wide', navigation: 'centered', headingScale: 'dramatic', headingCase: 'natural', imageShape: 'rectangle', separators: 'line' }, tokens: { primaryColor: '#D8B17B', secondaryColor: '#ACA499', accentColor: '#D8B17B', backgroundColor: '#181C1B', surfaceColor: '#242B28', textColor: '#F4EDE1', fontHeading: 'serif', fontBody: 'sans', borderRadius: 'subtle', buttonStyle: 'solid', cardStyle: 'bordered', spacingScale: 'generous', animationPreset: 'none' } },
  { id: 'street', name: 'Expressão urbana', description: 'Lima, grafite e tipografia forte em uma composição direta.', heroLayout: 'split', appearance: { width: 'wide', navigation: 'inline', headingScale: 'dramatic', headingCase: 'uppercase', imageShape: 'rectangle', separators: 'line' }, tokens: { primaryColor: '#D6EF78', secondaryColor: '#A1A59B', accentColor: '#D6EF78', backgroundColor: '#20231E', surfaceColor: '#2C3027', textColor: '#F5F6EC', fontHeading: 'display', fontBody: 'sans', borderRadius: 'none', buttonStyle: 'solid', cardStyle: 'bordered', spacingScale: 'comfortable', animationPreset: 'none' } },
  { id: 'botanical', name: 'Refúgio natural', description: 'Tons de argila, curvas orgânicas e uma atmosfera acolhedora.', heroLayout: 'split', appearance: { width: 'standard', navigation: 'inline', headingScale: 'expressive', headingCase: 'natural', imageShape: 'organic', separators: 'none' }, tokens: { primaryColor: '#4B5845', secondaryColor: '#6D7064', accentColor: '#955B3C', backgroundColor: '#F3EDE3', surfaceColor: '#FAF7F0', textColor: '#343B30', fontHeading: 'serif', fontBody: 'sans', borderRadius: 'rounded', buttonStyle: 'solid', cardStyle: 'elevated', spacingScale: 'generous', animationPreset: 'none' } },
  { id: 'precision', name: 'Estúdio essencial', description: 'Azul profundo, linhas limpas e atenção aos detalhes.', heroLayout: 'compact', appearance: { width: 'narrow', navigation: 'minimal', headingScale: 'restrained', headingCase: 'natural', imageShape: 'rectangle', separators: 'line' }, tokens: { primaryColor: '#233E64', secondaryColor: '#647080', accentColor: '#3D5E8C', backgroundColor: '#F7F9FC', surfaceColor: '#FFFFFF', textColor: '#243246', fontHeading: 'sans', fontBody: 'sans', borderRadius: 'subtle', buttonStyle: 'solid', cardStyle: 'bordered', spacingScale: 'comfortable', animationPreset: 'none' } },
  { id: 'heritage', name: 'Tradição autoral', description: 'Vinho, creme e uma presença clássica com fotografia em arco.', heroLayout: 'centered', appearance: { width: 'standard', navigation: 'centered', headingScale: 'expressive', headingCase: 'natural', imageShape: 'arch', separators: 'line' }, tokens: { primaryColor: '#662C37', secondaryColor: '#756560', accentColor: '#885234', backgroundColor: '#F7EFE3', surfaceColor: '#FFFAF1', textColor: '#412D2D', fontHeading: 'serif', fontBody: 'serif', borderRadius: 'subtle', buttonStyle: 'outline', cardStyle: 'minimal', spacingScale: 'generous', animationPreset: 'none' } },
  { id: 'monochrome', name: 'Preto no branco', description: 'Preto, branco e cinza. Sem cor, sem filigrana. Só conteúdo.', heroLayout: 'compact', appearance: { width: 'narrow', navigation: 'minimal', headingScale: 'restrained', headingCase: 'uppercase', imageShape: 'rectangle', separators: 'line' }, tokens: { primaryColor: '#1A1A1A', secondaryColor: '#757575', accentColor: '#1A1A1A', backgroundColor: '#FFFFFF', surfaceColor: '#F5F5F5', textColor: '#1A1A1A', fontHeading: 'sans', fontBody: 'sans', borderRadius: 'none', buttonStyle: 'solid', cardStyle: 'minimal', spacingScale: 'comfortable', animationPreset: 'none' } },
  { id: 'tropical', name: 'Sol e energia', description: 'Coral, turquesa e cantos arredondados para um clima descontraído.', heroLayout: 'split', appearance: { width: 'standard', navigation: 'inline', headingScale: 'expressive', headingCase: 'natural', imageShape: 'organic', separators: 'none' }, tokens: { primaryColor: '#E8654A', secondaryColor: '#5BB8A6', accentColor: '#F4A940', backgroundColor: '#FFF8F0', surfaceColor: '#FFFFFF', textColor: '#2D3436', fontHeading: 'sans', fontBody: 'sans', borderRadius: 'rounded', buttonStyle: 'solid', cardStyle: 'elevated', spacingScale: 'generous', animationPreset: 'subtle' } },
  { id: 'industrial', name: 'Concreto e aço', description: 'Cinza escuro, concreto bruto e tipografia condensada imponente.', heroLayout: 'fullscreen', appearance: { width: 'wide', navigation: 'inline', headingScale: 'dramatic', headingCase: 'uppercase', imageShape: 'rectangle', separators: 'line' }, tokens: { primaryColor: '#D4D4D4', secondaryColor: '#8A8A8A', accentColor: '#E07A3A', backgroundColor: '#1C1C1C', surfaceColor: '#2A2A2A', textColor: '#E8E8E8', fontHeading: 'display', fontBody: 'sans', borderRadius: 'none', buttonStyle: 'outline', cardStyle: 'bordered', spacingScale: 'comfortable', animationPreset: 'none' } },
];

export function applyDesignDirection(config: SiteEditorConfig, id: string): SiteEditorConfig {
  const direction = designDirections.find(item => item.id === id);
  if (!direction) throw new Error('Direção visual não encontrada.');
  // Parse creates independent nested data: never share mutable defaults between editors.
  return siteEditorConfigSchema.parse({ ...config, tokens: { ...config.tokens, ...direction.tokens }, content: { ...config.content, heroLayout: direction.heroLayout, appearance: { ...direction.appearance } } });
}
