ALTER TABLE "locations" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "services" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "professionals" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "appointments" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
